-- Seed Data V2 for KODYS Sample Reports
-- Ensure Patient UID is unique
INSERT INTO TX_PATIENTS (UID, NAME, LAST_NAME, SUR_NAME, FRIENDLY_UID, PREFIX, GENDER, AGE, ADDRESS_LINE_1, ZIPCODE, CREATED_ON, UPDATED_ON, CREATED_BY_id, UPDATED_BY_id, DATAMODE)
VALUES ('p_gold_999', 'John', 'Doe (Sample Data)', '', 'P-GOLD-001', 'Mr.', 'Male', 45, 'Sample Clinic, Chennai', '600001', datetime('now'), datetime('now'), 1, 1, 'A');

-- Doppler Sample (APP-01) - Master ID 1
INSERT INTO TX_MEDICALTESTS (UID, FRIENDLY_UID, MEDICALTESTMASTER_id, PATIENT_id, DOCTOR_id, REPORTED_ON, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('t_gold_01', 'TST-GOLD-01', 1, (SELECT id FROM TX_PATIENTS WHERE UID='p_gold_999'), 2, datetime('now'), datetime('now'), datetime('now'), 'A');

-- Doppler Entries (D-01 to D-08)
INSERT INTO TX_MEDICALTESTENTRIES (UID, MEDICALTEST_id, MEDICALTESTFIELDS_id, KEY_NAME, KEY_CODE, KEY_VALUE, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('e_g01_1', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_01'), 1, 'Right Brachial', 'D-01', '120', datetime('now'), datetime('now'), 'A');
INSERT INTO TX_MEDICALTESTENTRIES (UID, MEDICALTEST_id, MEDICALTESTFIELDS_id, KEY_NAME, KEY_CODE, KEY_VALUE, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('e_g01_2', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_01'), 2, 'Right Ankle', 'D-02', '140', datetime('now'), datetime('now'), 'A');
INSERT INTO TX_MEDICALTESTENTRIES (UID, MEDICALTEST_id, MEDICALTESTFIELDS_id, KEY_NAME, KEY_CODE, KEY_VALUE, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('e_g01_5', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_01'), 5, 'Left Brachial', 'D-05', '118', datetime('now'), datetime('now'), 'A');
INSERT INTO TX_MEDICALTESTENTRIES (UID, MEDICALTEST_id, MEDICALTESTFIELDS_id, KEY_NAME, KEY_CODE, KEY_VALUE, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('e_g01_6', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_01'), 6, 'Left Ankle', 'D-06', '135', datetime('now'), datetime('now'), 'A');

-- Doppler Report
INSERT INTO TX_MEDICALTESTREPORTS (UID, FRIENDLY_UID, MEDICALTEST_id, REPORTED_ON, TEST_STATUS, TEST_TYPE, CREATED_ON, UPDATED_ON, CREATED_BY_id, UPDATED_BY_id, DATAMODE)
VALUES ('r_gold_01', 'REP-GOLD-001', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_01'), datetime('now'), 'COMPLETED', 'ABI', datetime('now'), datetime('now'), 1, 1, 'A');

-- VPT Sample (APP-02) - Master ID 2
INSERT INTO TX_MEDICALTESTS (UID, FRIENDLY_UID, MEDICALTESTMASTER_id, PATIENT_id, DOCTOR_id, REPORTED_ON, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('t_gold_02', 'TST-GOLD-02', 2, (SELECT id FROM TX_PATIENTS WHERE UID='p_gold_999'), 2, datetime('now'), datetime('now'), datetime('now'), 'A');

-- VPT Entries (V-01 is Right Great Toe) - Assuming Field ID 20 based on previous analysis
INSERT INTO TX_MEDICALTESTENTRIES (UID, MEDICALTEST_id, MEDICALTESTFIELDS_id, KEY_NAME, KEY_CODE, KEY_VALUE, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('e_g02_1', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_02'), 20, 'Right Great Toe', 'V-01', '15', datetime('now'), datetime('now'), 'A');

-- VPT Report
INSERT INTO TX_MEDICALTESTREPORTS (UID, FRIENDLY_UID, MEDICALTEST_id, REPORTED_ON, TEST_STATUS, CREATED_ON, UPDATED_ON, CREATED_BY_id, UPDATED_BY_id, DATAMODE)
VALUES ('r_gold_02', 'REP-GOLD-002', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_02'), datetime('now'), 'COMPLETED', datetime('now'), datetime('now'), 1, 1, 'A');

-- Kodys CAN Sample (APP-07) - Master ID 26
INSERT INTO TX_MEDICALTESTS (UID, FRIENDLY_UID, MEDICALTESTMASTER_id, PATIENT_id, DOCTOR_id, REPORTED_ON, CREATED_ON, UPDATED_ON, DATAMODE)
VALUES ('t_gold_07', 'TST-GOLD-07', 26, (SELECT id FROM TX_PATIENTS WHERE UID='p_gold_999'), 2, datetime('now'), datetime('now'), datetime('now'), 'A');

-- CAN Entry with simulated peak list
INSERT INTO TX_MEDICALTESTREPORTS (UID, FRIENDLY_UID, MEDICALTEST_id, REPORTED_ON, TEST_STATUS, TEST_RESULT, CREATED_ON, UPDATED_ON, CREATED_BY_id, UPDATED_BY_id, DATAMODE)
VALUES ('r_gold_07', 'REP-GOLD-007', (SELECT id FROM TX_MEDICALTESTS WHERE UID='t_gold_07'), datetime('now'), 'COMPLETED', '{"resting": {"peaklist": [800, 1605, 2410, 3215, 4020]}}', datetime('now'), datetime('now'), 1, 1, 'A');
