"""
Django settings for app_config project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)

# DEFINE WRITABLE DATA ROOT (AppData)
if sys.platform == "darwin":
    DATA_ROOT = os.path.expanduser('~/Library/Application Support/KodysFootClinikV2')
else:
    DATA_ROOT = os.path.join(os.environ.get('TEMP', os.environ.get('TMP', os.path.expanduser('~'))), 'KodysFootClinikV2')

if not os.path.exists(DATA_ROOT):
    try:
        os.makedirs(DATA_ROOT)
    except:
        pass

# ENHANCED LOGGING DIR (v2.2.49)
if sys.platform == "win32":
    PERMANENT_LOG_DIR = r"C:\Program Files (x86)\Kodys Foot Clinik V2\logs"
    if not os.path.exists(PERMANENT_LOG_DIR):
        try:
            os.makedirs(PERMANENT_LOG_DIR)
        except:
            PERMANENT_LOG_DIR = os.path.join(DATA_ROOT, 'logs')
elif sys.platform == "darwin":
    # On Mac, we keep logs in the standard app data directory
    PERMANENT_LOG_DIR = os.path.join(DATA_ROOT, 'logs')
else:
    PERMANENT_LOG_DIR = os.path.join(DATA_ROOT, 'logs')

if not os.path.exists(PERMANENT_LOG_DIR):
    try: os.makedirs(PERMANENT_LOG_DIR)
    except: pass

# Ensure subdirs for media/data exist
for sub in ["app_assets", "app_assets/media", "app_assets/DATA"]:
    sub_path = os.path.join(DATA_ROOT, sub)
    if not os.path.exists(sub_path):
        try:
            os.makedirs(sub_path)
        except:
            pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^&6l41vym+d+o4s560lazu8#8-d_m(27mski$0x+wsvkd+&4+q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kodys',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"kodys/templates"),
                 os.path.join(BASE_DIR,"kodys/templates/pages"),
                 os.path.join(BASE_DIR,"kodys/templatetags"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
                'context_processors.app_config'
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_ROOT, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# ----------------------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(DATA_ROOT, 'static')

# We search in multiple probable locations to handle flattened installer structures
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "kodys", "templates", "gstatic"),             # Source Structure
    os.path.join(os.path.dirname(BASE_DIR), "kodys", "templates", "gstatic"), # Installer Flattened Structure
]

# Ensure they exist or remove to avoid Django 1.11 warnings
STATICFILES_DIRS = [d for d in STATICFILES_DIRS if os.path.exists(d)]

DATA_URL = '/site_data/'
MEDIA_URL = '/site_media/'
MEDIA_ROOT = os.path.join(DATA_ROOT, 'app_assets', 'media')
MEDIA_DATA = os.path.join(DATA_ROOT, 'app_assets', 'DATA')
DATA_UPLOAD_MAX_MEMORY_SIZE = 25000000

#########################################################################
#Kodys default user
#########################################################################
SERVICE_EMAIL = "kodysmedical001@gmail.com"
DEFAULT_USER_EMAIL = "kodysmedical001@gmail.com"
DEFAULT_USER_PASSWORD = "secret123!"
DEFAULT_USER_FIRSTNAME = "Kodys Administrator"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "kodysmedical001@gmail.com"
EMAIL_HOST_PASSWORD = "secret123!"
# LOGGING
##################################################################################################
LOGGER_FILE_NAME = "app"
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'custom': {
            'format': '%(asctime)s | NONE | NONE | %(levelname)s | %(filename)s:%(lineno)d | %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'null': {
            'class': 'logging.NullHandler',
         },
        'appfile':{
            'level':'DEBUG',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'custom',
            'filename': os.path.join(PERMANENT_LOG_DIR, 'app.log'),
            'when': 'W4',
            'interval': 1,
            'backupCount': 7
        },
        'console':{
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'app': {
            'handlers': ['appfile'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

LOGGING_CONFIG = 'logging.config.dictConfig'


RUNNING_IN_APP = True

ECG_TESTING_DURATION = "00:01:00"

ECG_HRV_TESTING_DURATION = "00:01:00"

# Use relative path so it works via localhost, ngrok, and cloudflare tunnels
MEDIA_URL = '/site_media/'
SA_ACCOUNTAPP_EMAIL_REGEX = '[a-zA-Z0-9_.\-\+]+@[a-zA-Z0-9\-\_]+\.[a-zA-Z0-9]+(\.[a-zA-Z0-9]{2,4}){0,2}$'


app_dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
if sys.platform == "win32":
    REPORT_TO_PDF_PATH = os.path.join(app_dir_path, 'wkhtmltopdf', 'bin', 'wkhtmltopdf.exe')
else:
    # On Mac/Linux, wkhtmltopdf should be in the system path or a relative bin
    REPORT_TO_PDF_PATH = 'wkhtmltopdf'
