"""app_config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
import django.views.static as django_static_view
from django.conf import settings
from kodys.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Hardened Static/Media Routes for Production Desktop Bundle
    url(r'^site_media/(?P<path>.*)$', django_static_view.serve, {'document_root': os.path.join(settings.BASE_DIR, "kodys/templates/gstatic") }),
    url(r'^static/(?P<path>.*)$', django_static_view.serve, {'document_root': os.path.join(settings.BASE_DIR, "kodys/templates/gstatic") }),
	url(r'^site_data/(?P<path>.*)$', django_static_view.serve, {'document_root': settings.MEDIA_DATA }),
    url(r'^static/admin/(?P<path>.*)$', django_static_view.serve,{'document_root': settings.STATIC_ROOT }),
    url(r'^about/$', about, name="about"),
    url(r'^signin/$', signin, name="signin"),
    url(r'^signout/$', signout, name="signout"),
	url(r'^$', home, name="home"),
    url(r'^customer/support/$', customer_support, name="customer_support"),
    url(r'^export/patients/$', export_patients_excel, name="export_patients_excel"),
    url(r'^hospital/profile/$', hospital_profile, name="hospital_profile"),
    url(r'^doctors/$', doctors, name="doctors"),
    url(r'^doctors/(?P<speciality>[-\d]+)/$', doctors, name="doctors"),
    url(r'^hcp/add/$', hcp_add, name="hcp_add"),
    url(r'^hcp/edit/(?P<hcp_uid>[-\w]+)/$', hcp_edit, name="hcp_edit"),
    url(r'^hcp/delete/(?P<hcp_uid>[-\w]+)/$', hcp_delete, name="hcp_delete"),
    url(r'^patients/$', patients, name="patients"),
    url(r'^patient/add/$', patients_add, name="patients_add"),
    url(r'^patient/edit/(?P<patients_uid>[-\w]+)/$', patients_edit, name="patients_edit"),
    url(r'^patient/delete/(?P<patients_uid>[-\w]+)/$', patients_delete, name="patients_delete"),
    url(r'^app/configuration/$', app_configuration, name="app_configuration"),
    url(r'^reports/$', reports, name="reports"),
    url(r'^reports/(?P<speciality>[-\w]+)/(?P<duration>[-\w]+)/$', reports, name="reports"),
    url(r'^manuals/$', manuals, name="manuals"),
    url(r'^manuals/(?P<category>[-\w]+)/$', manuals, name="manuals"),
    url(r'^report/view/canyscope/(?P<test_entry_code>[-\w]+)/$', canyscope_report_view, name="canyscope_report_view"),
    url(r'^report/view/(?P<test_entry_code>[-\w]+)/$', report_view, name="report_view"),
    url(r'^report/view/(?P<test_entry_code>[-\w]+)/(?P<mode>[-\w]+)/$', report_view, name="report_view"),
    url(r'^manuals/view/(?P<manuals_code>[-\w]+)/$', manuals_view, name="manuals_view"),
    url(r'^database/backup/$', database_backup, name="database_backup"),
    url(r'^restore/database/$', restore_database, name="restore_database"),
    url(r'^app/configuration/mail/(?P<key_code>[-\w]+)/$', app_configuration_mail, name="app_configuration_mail"),
    url(r'^app/configuration/settings/$', app_configuration_settings, name="app_configuration_settings"),
    url(r'^patient/search/(?P<search_key>[-\w]+)/$', patient_search, name="patient_search"),
    url(r'^patient/edit/search/(?P<patient_uid>[-\w]+)/(?P<search_key>[-\w]+)/$', patient_edit_search, name="patient_edit_search"),
    # url(r'^medical/test/entry/$', medical_test_entry, name="medical_test_entry"),
    # url(r'^medical/test/details/(?P<app_code>[-\w]+)/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', medical_test_details, name="medical_test_details"),
    # url(r'^APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/$', thermocool_foot, name="thermocool_foot"),
    url(r'^APP-01/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', doppler, name="doppler"),
    url(r'^APP-01/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', doppler, name="doppler"),
    url(r'^APP-01/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', doppler, name="doppler"),
    url(r'^graphical/APP-01/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', doppler_graphical, name="doppler_graphical"),
    url(r'^graphical/APP-01/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', doppler_graphical, name="doppler_graphical"),
    url(r'^graphical/template/upload/$', doppler_graphical_template, name="doppler_graphical_template"),
    url(r'^APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', vpt_foot, name="vpt_foot"),
    url(r'^APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_foot, name="vpt_foot"),
    url(r'^APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_foot, name="vpt_foot"),
    url(r'^hand/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_hand, name="vpt_hand"),
    url(r'^hand/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_hand, name="vpt_hand"),
    url(r'^hand/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', vpt_hand, name="vpt_hand"),    
    url(r'^APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', vpt_ultra_foot, name="vpt_ultra_foot"),
    url(r'^APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_ultra_foot, name="vpt_ultra_foot"),
    url(r'^APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_ultra_foot, name="vpt_ultra_foot"),
    url(r'^hand/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_ultra_hand, name="vpt_ultra_hand"),
    url(r'^hand/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_ultra_hand, name="vpt_ultra_hand"),
    url(r'^hand/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', vpt_ultra_hand, name="vpt_ultra_hand"),
    url(r'^APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', thermocool_foot, name="thermocool_foot"),
    url(r'^APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', thermocool_foot, name="thermocool_foot"),
    url(r'^APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', thermocool_foot, name="thermocool_foot"),
    url(r'^APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', thermocool_foot, name="thermocool_foot"),
    url(r'^hand/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', thermocool_hand, name="thermocool_hand"),
    url(r'^hand/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', thermocool_hand, name="thermocool_hand"),
    url(r'^hand/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', thermocool_hand, name="thermocool_hand"),
    url(r'^generate/report/(?P<test_uid>[-\w]+)/$', generate_report, name="generate_report"),
    url(r'^test/patient/edit/(?P<patient_uid>[-\w]+)/(?P<app_code>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', test_patient_edit, name="test_patient_edit"),
    url(r'^test/patient/hand/edit/(?P<patient_uid>[-\w]+)/(?P<app_code>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', test_patient_hand_edit, name="test_patient_hand_edit"),
    url(r'^test/patient/other/edit/(?P<patient_uid>[-\w]+)/(?P<app_code>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', test_patient_other_edit, name="test_patient_other_edit"),
    url(r'^test/impression/$', test_impression, name="test_impression"),
    url(r'^device-config-save/(?P<app_code>[-\w]+)/$', device_config_save, name="device_config_save"),
    url(r'^test/referred/$', test_referred, name="test_referred"),
    url(r'^email/report/$', email_report, name="email_report"),
    # url(r'^other/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', thermocool_other, name="thermocool_hand"),
    url(r'^other/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', thermocool_other, name="thermocool_hand"),
    url(r'^other/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', thermocool_other, name="thermocool_other"),
    url(r'^other/APP-04/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', thermocool_other, name="thermocool_other"),
    url(r'^other/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_ultra_other, name="vpt_ultra_other"),
    url(r'^other/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_ultra_other, name="vpt_ultra_other"),
    url(r'^other/APP-03/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', vpt_ultra_other, name="vpt_ultra_other"),
    url(r'^other/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', vpt_other, name="vpt_other"),
    url(r'^other/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', vpt_other, name="vpt_other"),
    url(r'^other/APP-02/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', vpt_other, name="vpt_other"),
    url(r'^generate/license/$', generate_license, name="generate_license"),
    url(r'^patient/email/$', patient_email, name="patient_email"),
    url(r'^patient/id/search/(?P<search_key>[-\w]+)/$', patient_id_search, name="patient_id_search"),
    url(r'^test/patient/graphical/edit/(?P<patient_uid>[-\w]+)/(?P<app_code>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', test_patient_graphical_edit, name="test_patient_graphical_edit"),
    url(r'^APP-05/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', podo_i_mat, name="podo_i_mat"),
    url(r'^APP-05/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', podo_i_mat, name="podo_i_mat"),
    url(r'^APP-05/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', podo_i_mat, name="podo_i_mat"),
    # url(r'^APP-05/foot/convert/$', podo_i_mat_foot_convert, name="podo_i_mat_foot_convert"),
    url(r'^APP-06/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', podo_t_map, name="podo_t_map"),
    url(r'^APP-06/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', podo_t_map, name="podo_t_map"),
    url(r'^APP-06/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', podo_t_map, name="podo_t_map"),
    url(r'^APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/$', kodys_can, name="kodys_can"),
    url(r'^APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', kodys_can, name="kodys_can"),
    url(r'^APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', kodys_can, name="kodys_can"),
    url(r'^sympathetic/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', kodys_can_sympathetic, name="kodys_can_sympathetic"),
    url(r'^sympathetic/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', kodys_can_sympathetic, name="kodys_can_sympathetic"),
    url(r'^sympathetic/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', kodys_can_sympathetic, name="kodys_can_sympathetic"),
    url(r'^hrv/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', kodys_can_hrv, name="kodys_can_hrv"),
    url(r'^hrv/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/$', kodys_can_hrv, name="kodys_can_hrv"),
    url(r'^hrv/APP-07/(?P<patient_uid>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/(?P<test_entry>[-\w]+)/(?P<previous_test_code>[-\w]+)/$', kodys_can_hrv, name="kodys_can_hrv"),
    url(r'^test/patient/hrv/edit/(?P<patient_uid>[-\w]+)/(?P<app_code>[-\w]+)/(?P<doctor_uid>[-\w]+)/(?P<examiner_uid>[-\w]+)/(?P<test_code>[-\w]+)/$', test_patient_hrv_edit, name="test_patient_hrv_edit"),
    ]
