# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-14 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOPPLER_GRAPHICAL_PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BASE_64_IMAGES', jsonfield.fields.JSONField()),
                ('CREATED_ON', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_ON', models.DateTimeField(auto_now=True)),
                ('DATAMODE', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive'), (b'D', b'Deleted')], default='A', max_length=1)),
                ('CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doppler_graphical_pdf_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'DOPPLER_GRAPHICAL_PDF',
            },
        ),
        migrations.CreateModel(
            name='TX_HCP_SPECIALIZATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATAMODE', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive'), (b'D', b'Deleted')], default='A', max_length=1)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'TX_HCP_SPECIALIZATION',
            },
        ),
        migrations.RemoveField(
            model_name='ma_hcp_specialization',
            name='TYPE',
        ),
        migrations.RemoveField(
            model_name='tx_hcp',
            name='SPECIALIZATION',
        ),
        migrations.RemoveField(
            model_name='tx_hcp',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='tx_medicaltests',
            name='IMPRESSION_NOTES',
        ),
        migrations.AddField(
            model_name='ma_hcp_specialization',
            name='MEDICAL_APP',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodys.MA_MEDICALAPPS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ma_medicalappdevices',
            name='DEVICE_CONFIG',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ma_medicalappdevices',
            name='DEVICE_MORE_OPTION',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ma_medicaltestinstruction',
            name='INSTRUCTION_IMAGE',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ma_medicaltestmaster',
            name='ORGAN_TYPE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ma_medicaltestmaster',
            name='REFERRED_BY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tx_account',
            name='IS_REPORT_HEADER',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tx_applicationservicerequests',
            name='HOSPITAL_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tx_hcp',
            name='ACCOUNTUSER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodys.TX_ACCOUNTUSER'),
        ),
        migrations.AddField(
            model_name='tx_hcp',
            name='PREFIX',
            field=models.CharField(choices=[(b'Dr.', b'Dr.'), (b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Miss.', b'Miss.')], default=' ', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tx_medicaltestentries',
            name='KEY_VALUE_STATUS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='CREATED_BY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tx_medicaltestreports_createdby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='IMPRESSION_NOTES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='REFERRED_BY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='TEMPERATURE_SCALE',
            field=models.CharField(blank=True, choices=[(b'CELSIUS', b'Celsius'), (b'FAHRENHEIT', b'Fahrenheit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='TEST_RESULT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='TEST_STATUS',
            field=models.CharField(choices=[(b'COMPLETED', b'Completed'), (b'INCOMPLETE', b'Incomplete')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='TEST_TYPE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tx_medicaltestreports',
            name='UPDATED_BY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tx_medicaltestreports_updatedby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tx_patients',
            name='PREFIX_DIGITS_LENGTH',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ma_application_contacts',
            name='MOBILE_NUMBER',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ma_application_manuals',
            name='SUB_CATEGORY',
            field=models.CharField(choices=[(b'DOPPLER', b'Doppler'), (b'PODOIMAT', b'Podo I Mat'), (b'PODOTMAP', b'Podo T Map'), (b'BIOTHEZIVPT', b'Biothezi VPT'), (b'BIOTHEZIVPTULTRA', b'Biothezi VPT Ultra'), (b'KODYSHCPELITE', b'Kodys HCP Elite'), (b'KODYSCAN', b'Kodys CAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ma_medicaltestfields',
            name='KEY_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='BUSINESS_SHORT_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='BUSINESS_SHORT_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='CITY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='COUNTRY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='FAX_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='MOBILE_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='STATE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tx_account',
            name='ZIPCODE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tx_accountuser',
            name='LAST_LOGIN',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx_applicationservicerequests',
            name='ACCOUNT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodys.TX_ACCOUNT'),
        ),
        migrations.AlterField(
            model_name='tx_hcp',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tx_hcp',
            name='GENDER',
            field=models.CharField(choices=[(b'MALE', b'Male'), (b'FEMALE', b'Female'), (b'TRANSGENDER', b'Transgender')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tx_hcp',
            name='MOBILE_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tx_medicaldevicestatus',
            name='CONNECTION_TYPE',
            field=models.CharField(choices=[(b'USB', b'USB'), (b'BLUETOOTH', b'BLUETOOTH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tx_medicaltestentries',
            name='KEY_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tx_medicaltestentries',
            name='KEY_VALUE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx_medicaltestreports',
            name='REPORT_PATH',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx_medicaltests',
            name='DOCTOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_medicaltests_doctor', to='kodys.TX_HCP'),
        ),
        migrations.AlterField(
            model_name='tx_medicaltests',
            name='EXAMINER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_medicaltests_examiner', to='kodys.TX_HCP'),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='ADDRESS_LINE_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='ADDRESS_LINE_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='CITY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='COUNTRY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodys.MA_COUNTRY'),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='GENDER',
            field=models.CharField(choices=[(b'MALE', b'Male'), (b'FEMALE', b'Female'), (b'TRANSGENDER', b'Transgender')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='HEIGHT',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='PATIENT_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='PATIENT_MOBILE_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='POC_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='POC_MOBILE_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='PREFIX',
            field=models.CharField(choices=[(b'Mr.', b'Mr.'), (b'Mrs.', b'Mrs.'), (b'Miss.', b'Miss.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='STATE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kodys.MA_STATE'),
        ),
        migrations.AlterField(
            model_name='tx_patients',
            name='WEIGHT',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tx_hcp_specialization',
            name='HCP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodys.TX_HCP'),
        ),
        migrations.AddField(
            model_name='tx_hcp_specialization',
            name='SPECIALIZATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodys.MA_HCP_SPECIALIZATION'),
        ),
        migrations.AddField(
            model_name='doppler_graphical_pdf',
            name='TEST_REPORT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodys.TX_MEDICALTESTREPORTS'),
        ),
        migrations.AddField(
            model_name='doppler_graphical_pdf',
            name='UPDATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doppler_graphical_pdf_updatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
